server:
  port: 8020
spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
  datasource:
    url:
    username: root
    password: root
    driver-class-name: